### ISSUE TITLE
Redbot: Add java 17

### ISSUE THREAD

**Issue by MegaShinySnivy** [JJGadgets/containers#35]
The audio cog, a very commonly used cog for redbot, requires Java 11 or 17 installed in order to be able to function. If possible I'd like to have this added to the container, as its a common cog dependency. Note: normally I would just make a PR, but I can't seem to get a fork of this repo functioning.

https://docs.discord.red/en/stable/cog_guides/audio.html

**Comment by MegaShinySnivy** [comment]
As discussed on discord: another option would be to include lavalink as another container, possibly based off of https://github.com/lavacord/Lavalink-Dockerfile

**Comment by JJGadgets** [comment]
https://github.com/JJGadgets/Biohazard/issues/522

**Comment by JJGadgets** [comment]
We both have had Lavalink running within the main RedBot container for a while now, so this can be marked closed.
